prgrms-web-devcourse/Team-Saiko-BidMarket-BE

.github/workflows/unit-test.yml, build.gradle
- 테스트 및 테스트 커버리지 리포트 자동화 CI 입니다
- 아래와 같이 테스트 코드가 추가되는 경우 테스트 커버리지를 측정한 codecov 코멘트가 달리게 됩니다.
- [CodecovTest.java](https://github.com/prgrms-web-devcourse/Team-Saiko-BidMarket-BE/pull/1/files#diff-f2dc2552200982fcde5ea414cf46f5622dc1e3f59019e75e11d1adef4dbcedb0) 파일은 샘플파일이며 merge직전 삭제할 예정입니다.
- PR이름, 브랜치 이름은 스프린트가 시작하면 변경하도록 하겠습니다. [티켓번호] 테스트 및 테스트 커버리지 리포트 자동화 CI
=> [BM-97] 테스트 및 테스트 커버리지 리포트 자동화 CI 입니다

build.gradle, src/main/resources/application.yaml
- 구글 OAuth 클라이언트 생성하였고, 클라이언트 id, secret key 는 Repository secrets에 등록해 두었습니다.
- security, oauth-client, auth0 및 인자 검증(isNotEmpty(), isNotBlank(), ...)을 위한 apach common lang 의존성을 추가하였습니다.
=> [BM-61] OAuth2 인증관련 의존성 및 환경변수 추가

.github/workflows/sonarqube.yml, build.gradle
우선 적용하고 싶었던 기능은 소나 큐브 분석 결과를 해당 PR에 comment가 달리도록 하고 싶었지만 깃헙 액션을 활용해 코멘트를 다는 방법을 찾지 못했습니다. 그래서 차선책으로 분석 결과 링크를 제공하도록 변경했습니다. 
아래와 같이 소나큐브 호스트 링크를 제공하고 분석 결과를 확인할 수 있습니다.
`BidMarket-pr number` 의 분석 결과를 확인하면 됩니다
Bug, Critical 혹은 Major 부분만 확인하면 코드 리뷰를 받기 전 실수나 개선점을 확인할 수 있을것 같긴합니다. 
적용하다가 별로다 싶으면 로컬에 소나 린트를 적용하거나 리뷰를 더 주의해서 살펴보면 충분히 커버할 수 있는 부분이라
해보다가 별로면 버려도 될것 같습니다~~
=> [BM-99] 소나 큐브 정적 분석 CI 적용

build.gradle, src/main/java/com/saiko/bidmarket/user/entity/Group.java, src/main/java/com/saiko/bidmarket/user/entity/GroupPermission.java, src/main/java/com/saiko/bidmarket/user/entity/Permission.java, src/main/java/com/saiko/bidmarket/user/entity/User.java, src/main/resources/application.yaml, src/main/resources/sql/product/product_schema.sql, src/main/resources/sql/schema.sql, src/main/resources/sql/user/user_data.sql, src/main/resources/sql/user/user_schema.sql
- #9 와 DB 관련 설정부분들이 일부 겹치는데 이러한 부분은 제외하고 봐주시면 될것 같습니다.
- 닉네임을 principal로 쓸경우 닉네임을 변경할 때 마타 토큰을 재발급 해야합니다.
- 이메일을 oauth 로 받아서 principal로 쓸 수 있도록 엔티티를 구성하였습니다.
- 권한 정보가 코드상에 노출되지 않는다는 장점때문에 차용하였습니다.
- 토큰에 권한 정보가 포함되어있기 때문에 토큰 발급시 외에는 추가적인 쿼리가 발생하지 않을것입니다. 
- <img width="410" alt="image" src="https://user-images.githubusercontent.com/28651727/180967991-b784a4b4-7106-44e3-a012-10bcf021a100.png">
- #9 pr이 머지되면 수정하여 반영하겠습니다.
=> [BM-52] User, Group, Permission 엔티티 정의

src/main/java/com/saiko/bidmarket/common/exception/NotFoundException.java, src/main/java/com/saiko/bidmarket/user/repository/GroupRepository.java, src/main/java/com/saiko/bidmarket/user/repository/UserRepository.java, src/main/java/com/saiko/bidmarket/user/service/DefaultGroupService.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/main/java/com/saiko/bidmarket/user/service/GroupService.java, src/main/java/com/saiko/bidmarket/user/service/UserService.java, src/test/java/com/saiko/bidmarket/user/service/DefaultGroupServiceTest.java, src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
provider 와 providerId를 통해 유저가 존재하는지 확인하고 존재하지 않으면 유저를 생성하고 저장하는 로직을 구현하였습니다.
유저가 존재하지 않는경우를 위해 NotFoundException 예외를 추가하였습니다.
=> [BM-52] UserService 회원가입 구현 및 테스트

src/main/java/com/saiko/bidmarket/product/Category.java, src/main/java/com/saiko/bidmarket/product/controller/ProductDetailResponse.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
- Enum Type은 기본적으로 Oridinal(순서)와 Name(이름 - 빨간색)을 가지고 있습니다.
- 여기에 필요에 따라 추가적인 필드 값들을 구현할 수 있는 데, 저희가 사용하는 Category에 name이라는 필드(노란색)를 추가하였습니다.
- 기본적으로 가지고 있는 Name에 대한 조회 함수는 `name()`이고 추가한 name 필드 조회 함수는 `getName()`입니다.
- 응답객체에서는 `getName()`을 통해 새로 정의된 name을 가져 와야 하는데 `name()`함수로 기본 name을 가져오고 있어서 수정하였습니다.
name이라는 필드명 자체가 헷갈릴 여지가 있어서 필드명을 변경하는 것도 고려해보면 좋을 것 같습니다!
=> [BM-128] :bug: 상품 상세조회 응답 객체 카테고리 필드 수정

build.gradle, src/docs/asciidoc/api.adoc
* Rest Docs 적용을 위하여 Asciidoc 설정을 추가하였습니다.
* 적용 방법
1. Controller 테스트 작성
2. Controller 테스트 돌리기
3. `/build/generated-snippets/XX` 경로로 들어가면 Controller 테스트에 해당하는 adoc 파일이 생성된 것을 확인할 수 있음
4. `/src/docs/asciidoc/api.adoc` 파일 내에 API에 해당하는 명세 작성 (adoc 파일 추가)
=> [BM-124] Rest Docs Asciidoc 설정

src/main/java/com/saiko/bidmarket/common/jwt/Jwt.java, src/main/java/com/saiko/bidmarket/common/jwt/JwtAuthentication.java, src/main/java/com/saiko/bidmarket/common/jwt/JwtAuthenticationFilter.java, src/main/java/com/saiko/bidmarket/common/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/saiko/bidmarket/user/entity/User.java, src/main/resources/application.yaml
기존 JWT 검증 관련 로직에 문제가 있어서 수정했습니다.
username -> userId
유저 관련 노출 정보 삭제
테스트 화면입니다.
컨트롤러에서 유저 ID를 받으려면 메서드 인자로
`@AuthenticationPrincipal JwtAuthentication authentication`
을 받고 `authentication.getUserId()` 로 접근할 수 있습니다. 
이 UserId는 String 타입입니다.
예시 
```  
public ProductCreateResponse create(
@AuthenticationPrincipal JwtAuthentication athentication
@RequestBody @Valid ProductCreateRequest productCreateRequest) {
long productId = productService.create(
productCreateRequest,
athentication.userId
)
return ProductCreateResponse.from(productId);
}
```
=> [BM-92] JWT 관련 수정

src/main/java/com/saiko/bidmarket/common/jwt/Jwt.java, src/main/java/com/saiko/bidmarket/common/jwt/JwtAuthentication.java, src/main/java/com/saiko/bidmarket/common/jwt/JwtAuthenticationFilter.java, src/main/java/com/saiko/bidmarket/common/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/java/com/saiko/bidmarket/product/service/ProductService.java, src/main/java/com/saiko/bidmarket/user/entity/User.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java, src/test/java/com/saiko/bidmarket/util/WithMockCustomLoginUser.java, src/test/java/com/saiko/bidmarket/util/WithMockCustomLoginUserSecurityContextFactory.java
이번 PR은 두 가지 내용이있습니다
많지 않아서 합쳤어요 (파일 개수만 많지 코드 변경은 적어요!) 많다 싶으면 코멘트 남겨주세요 다음 PR시 양조절 하겠습니다!
확인 결과 
---
**컨트롤러  : `@AuthenticationPrincipal JwtAuthentication authentication` 을 인자로 받고 `authentication.getUserId`로 접근**
**테스트 : 유저 정보를 받는 controller 메서드 테스트시 `@WithMockCustomLoginUser` 추가**
=> [BM-136] 상품 등록 API 코드 수정 (토큰 인증, 유저 정보를 받도록), Token에 UserId를 Long타입으로 받도록 변경

build.gradle, src/main/java/com/saiko/bidmarket/product/Sort.java, src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java, src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java, src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectResponse.java, src/main/java/com/saiko/bidmarket/product/entity/Image.java, src/main/java/com/saiko/bidmarket/product/entity/Product.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/java/com/saiko/bidmarket/product/service/ProductService.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
* 현재는 기본 정렬 조건으로 "종료 임박 순"으로 구현하였습니다. 하지만 정렬 조건이 추후에 추가 될 수도 있는데 동적 쿼리를 jpql 을 사용하거나 criterial 를 사용해서 짜게 되면 유지보수가 어렵고 코드의 가독성이 너무 떨어지기 때문에 querydsl을 사용하는게 좋을 것 같다고 생각했습니다!
* Criterial 참고
* Criterial 사용시 아래 처럼 작성됨
* 문자가 아닌 자바코드로 JPQL을 작성할 수 있음
* JPA 공식 기능
* 단점: 너무 복잡하고 실용성이 없다.
* Criterial 대신에 QueryDSL 사용 권장
=> [BM-130] :sparkles: 상품 전체 조회 controller 구현

src/main/java/com/saiko/bidmarket/product/controller/ProductDetailResponse.java, src/main/java/com/saiko/bidmarket/product/controller/dto/ImagBasicResponse.java, src/main/java/com/saiko/bidmarket/product/entity/Image.java, src/main/java/com/saiko/bidmarket/product/entity/Product.java, src/main/java/com/saiko/bidmarket/user/entity/User.java, src/main/java/com/saiko/bidmarket/user/entity/dto/UserBasicResponse.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
- 빨간색 부분이 추가 되었습니다.
- 상품 상세 조회 관련해서 프론트에서 작성자 정보를 추가로 요청하여서 해당 요청 반영
- 상품 객체 변경에 따른 상품 이미지 정보도 응답 객체에 추가
- 이미지 응답용 객체 정의
- 응답 객체에 작성자와 상품 이미지 주소 리스트 추가
- 불필요한 어노테이션 삭제
=> [BM-143] 상품 상세 조회 응답 변경에 따른 수정사항 반영

src/main/resources/application.yaml
- sql 초기화시 oauth2-client-schema 테이블이 존재하면 drop 하는 로직이 빠져있어 수정하였습니다.
- 운영 데이터가 쌓이면 `drop table if exist` 로 관리하지 말고 flyway를 사용해야 할것같습니다.
=> [BM-141] sql 누락 수정

src/main/java/com/saiko/bidmarket/user/entity/User.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
Service 레이어의 회원 정보 수정 기능 테스트와 프로덕션 코드를 구현했습니다.
- User Entity에 update 메서드를 추가했습니다.
- UserService에 update 메서드를 추가했습니다. 
- 해당 메서드 테스트 코드를 작성했습니다.
entity의 update 메서드에서 인자 검증 의미가 있는 검증일까요?
=> [BM-142] 회원 정보 수정 Service 메서드 구현

src/main/java/com/saiko/bidmarket/common/exception/ExceptionController.java, src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepository.java, src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java, src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
- 유저가 판매한 상품목록을 조회하는 QueryDSL 메서드를 작성하였습니다.
- 상품목록에 유저의 정보는 불필요하므로 inner join으로 작성하였습니다.
```
Hibernate: 
select
product0_.id as id1_7_,
product0_.created_at as created_2_7_,
product0_.updated_at as updated_3_7_,
product0_.category as category4_7_,
product0_.description as descript5_7_,
product0_.expire_at as expire_a6_7_,
product0_.location as location7_7_,
product0_.minimum_price as minimum_8_7_,
product0_.thumbnail_image as thumbnai9_7_,
product0_.title as title10_7_,
product0_.user_id as user_id11_7_ 
from
inner join
`user` user1_ 
on product0_.user_id=user1_.id 
where
user1_.id=? 
order by
```
- Assertion 을 통해 검증하였을때 IllegalArgumentException 이 발생하여야 하는데 QueryDSL 이 InvalidDataAccessApiUsageException 으로 감싸서 에러를 발생시키는것같습니다. 이부분은 …
=> [BM-179] findAllUserProduct QueryDSL 메서드 작성

src/main/java/com/saiko/bidmarket/common/exception/ExceptionController.java, src/main/java/com/saiko/bidmarket/product/Category.java, src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java, src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepository.java, src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java, src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
* 전체 조회와 구현이 똑같아서 동일한 컨트롤러(/api/v1/products)로 요청 보내도록 했습니다. 
* 우선 카테고리 검색 & 종료 임박순 정렬 구현하였습니다. 필요한 부분은 추후에 기능 추가하면 될 것 같습니다.
* 카테고리 정보가 넘어오지 않는다면 전체 카테고리 상품 목록을 조회합니다.
* 카테고리 추가 안함
```java
Hibernate: 
select
product0_.id as id1_7_,
product0_.created_at as created_2_7_,
product0_.updated_at as updated_3_7_,
product0_.category as category4_7_,
product0_.description as descript5_7_,
product0_.expire_at as expire_a6_7_,
product0_.location as location7_7_,
product0_.minimum_price as minimum_8_7_,
product0_.thumbnail_image as thumbnai9_7_,
product0_.title as title10_7_,
product0_.user_id as user_id11_7_ 
from
order by
```
* 카테고리 포함 검색
```java
Hibernate: 
select
product0_.id as id1_7_,
product0_.created_at as created_2_7_,
product0_.updated_at …
```
=> [BM-176] :sparkles: 상품 검색 api 구현

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java, src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectRequest.java, src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectResponse.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/main/java/com/saiko/bidmarket/user/service/UserService.java, src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
```
Response
[
{
"id": Number,
"title": String,
"thumbnailImage": String,
"minimumPrice": Number,
"expireAt": Date,
"createdAt": Date,
"updatedAt": Date,
},
{} // 유사 데이터 limit 개수만큼 반환
]	
```
=> [BM-186] 유저 판매 내역 조회 Controller 구현입니다.

src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java, src/main/java/com/saiko/bidmarket/product/repository/ProductRepository.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/java/com/saiko/bidmarket/product/service/ProductService.java, src/test/java/com/saiko/bidmarket/product/SchedulerTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
매 분마다 해당 시간에 종료되는 경매가 있는지 확인하고, 있다면 경매 종료 로직을 수행하도록 하는 스케줄러를 구현하였습니다.
경매 종료 백엔드 로직에 해당하는 것은 다음 PR 때 올라올 예정입니다.
=> [BM-67] 경매 종료 스케줄러 구현

src/main/java/com/saiko/bidmarket/bidding/controller/BiddingController.java, src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java, src/test/java/com/saiko/bidmarket/bidding/controller/BiddingControllerTest.java, src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java
- 비딩 시 상품의 진행 상태를 검증하는 로직 및 테스트 추가
- `product.isProgressed() ` 활용하여 진행하지 않을 경우 비딩되지 않도록 하였습니다.
- 비딩 api path 복수형으로 변경
=> [BM-191] 비딩 상품 진행 상태 검증 로직 추가

src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java, src/main/java/com/saiko/bidmarket/product/controller/dto/ProductDetailResponse.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/java/com/saiko/bidmarket/product/service/ProductService.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
- 상품 상세 조회 응답 객체의 필드명 변경 (프론트 요청 사항)
- categoryName ⇒ category
- imageUrls ⇒ images
- 상세 조회 응답 dto가 dto 패키지가 아니라 밖에 있어서 이동
- 응답 객체에 롬복 getter 적용
실수로 main  update를 merge로 해서 다시 올립니다.
=> [BM-190] 상품 상세 조회 API 변경 사항 반영

src/test/java/com/saiko/bidmarket/product/SchedulerTest.java
`.atMost(Duration.ofSeconds(119))` : 60초 -> 119초로 변경하였습니다.
=> [BM-193] 경매 종료 스케줄러 테스트 시간 수정

src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java
- Bidding Entity의 Fetch Type을 Lazy에서 Eager로 변경
- 비딩 금액만으로는 무언가를 표현할 수 없어서 상품과 비딩한 유저의 정보가 늘 필요하다고 생각해서 변경하였습니다.
=> [BM-195] Bidding Fk Fetch Type 변경(Lazy -> EAGER)

src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java, src/main/java/com/saiko/bidmarket/bidding/respository/BiddingRepository.java, src/main/java/com/saiko/bidmarket/bidding/service/BiddingService.java, src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java, src/main/java/com/saiko/bidmarket/product/entity/Product.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/resources/sql/bidding/bidding_schema.sql, src/main/resources/sql/product/product_schema.sql, src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
* 경매 종료시 수행되는 비즈니스 로직을 구현하였습니다.
* 기획서에 작성된 내용은 다음과 같습니다.
* ![image](https://user-images.githubusercontent.com/78195316/182621627-31927099-bc0d-41f6-afdc-bdb8a3428e4c.png)
* 경매 종료시 로직 흐름은 다음과 같습니다.
1. Bidding 상태값 변경
2.  최고 가격을 제시한 Bidder가 낙찰
* 낙찰 가격 =  2등 입찰 가격 + 1000원
* 입찰자가 한 명이라면 최소 금액(minimumPrice)으로 낙찰
3. Product 경매 상품 상태값 변경
* 경매에 입찰한 입찰자가 한 명도 존재하지 않을 경우의 로직은 구현하지 않았습니다. (`DefaultBiddingService` 클래스 내부 메소드에 주석 처리해 둠)
* 내일 기획 논의 후 기능 추가하도록 하겠습니다.
=> [BM-187] 경매 종료 비즈니스 로직 구현

src/main/java/com/saiko/bidmarket/bidding/respository/BiddingCustomRepository.java, src/main/java/com/saiko/bidmarket/bidding/respository/BiddingCustomRepositoryImpl.java, src/main/java/com/saiko/bidmarket/bidding/respository/BiddingRepository.java, src/main/java/com/saiko/bidmarket/product/Category.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/main/resources/sql/bidding/bidding_schema.sql, src/test/java/com/saiko/bidmarket/bidding/repository/BiddingRepositoryTest.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java, src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java, src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
* 입찰 목록 조회 service, repository 구현 하였습니다.
```java
Hibernate: 
select
bidding0_.id as id1_0_0_,
product1_.id as id1_7_1_,
user2_.id as id1_8_2_,
bidding0_.created_at as created_2_0_0_,
bidding0_.updated_at as updated_3_0_0_,
bidding0_.`bidder_id` as bidder_i5_0_0_,
bidding0_.bidding_price as bidding_4_0_0_,
bidding0_.product_id as product_6_0_0_,
product1_.created_at as created_2_7_1_,
product1_.updated_at as updated_3_7_1_,
product1_.category as category4_7_1_,
product1_.description as descript5_7_1_,
product1_.expire_at as expire_a6_7_1_,
product1_.location as location7_7_1_,
product1_.minimum_price as minimum_8_7_1_,
product1_.progressed as progress9_7_1_,
product1_.thumbnail_image as thumbna10_7_1_,
product1_.title as title11_7_1_,
product1_.user_id as user_id12_7_1_,
user2_.created_at …
```
=> [BM-189] :sparkles: 입찰 목록 조회 service, repository 구현

src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java, src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java, src/test/java/com/saiko/bidmarket/bidding/repository/BiddingRepositoryTest.java, src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java, src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
- 상품 최소 금액 검증 로직 및 테스트 추가, 수정
- 기획 상 상품의 최소 금액 이상의 금액을 비딩해야 하고 이보다 적은 금액은 비딩되지 않도록 해야 되는데 해당 부분이 누락되어 있었습니다. 
- 이 부분에 대한 로직을 도메인 객체에 추가 및 테스트 구현 하였습니다.
- 추가로 기존 테스트 중에 비딩 금액이 상품 최소 금액보다 작은 케이스가 있어서 수정하였습니다.
=> [BM-198] 상품 최소 금액 검증 로직 및 테스트 추가, 수정

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java, src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
상품 목록 조회 로그인 하지않고 접근 가능하도록 수정했습니다.
Long Id로 하려다가 저희 회원 정보 조회 응답이 String이라 프론트에서 인코딩된 값을 가지고 있기때문에 동일하게 인코딩 아이디로 받습니다. 이부분은 나중에 전체적인 수정 진행하면 될것 같습니다.
=> [BM-199] :recycle: 판매 상품 목록 조회 인증안하고 접근 가능하도록 수정

src/main/java/com/saiko/bidmarket/product/Sort.java, src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java, src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java, src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
* 검색 조건 추가하였습니다.
* 입찰 진행 중인 상품 필터 검색 
* 정렬 조건 추가
* 최신순
* 시작가 오름차순
* 시작가 내림차순
=> [BM-203] :sparkles: 상품 검색 조건 추가 구현

src/main/java/com/saiko/bidmarket/bidding/service/BiddingService.java, src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java, src/main/java/com/saiko/bidmarket/product/entity/Product.java, src/main/resources/sql/product/product_schema.sql, src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java
* Product 엔티티 winningPrice 필드 타입을 long -> Long 타입으로 변경
* 비딩한 사람이 없을 경우 null 삽입
=> [BM-245] 경매 종료시 비딩한 사람이 없을 때의 로직 추가

src/main/java/com/saiko/bidmarket/comment/entity/Comment.java, src/main/resources/application.yaml, src/main/resources/sql/comment/comment_schema.sql, src/main/resources/sql/product/product_schema.sql, src/main/resources/sql/user/user_schema.sql
* 우선 product 엔티티와 동일하게 길이 제한을 500으로 하였습니다.
* product, user created_at컬럼에 not null 추가했습니다.
=> [BM-248] :sparkles: 댓글 엔티티 구현

src/main/resources/application.yaml
현재 application.yaml 파일에 sql 순서 문제로 서버 실행시 에러가 발생합니다. 
(DROP 문 실행시 외래키 에러)
notification.sql 을 product.sql 앞으로 이동했습니다.
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #2 of class path resource [sql/product/product_schema.sql]: DROP TABLE IF EXISTS `product` CASCADE; nested exception is java.sql.SQLException: Cannot drop table 'product' referenced by a foreign key constraint 'FK_PRODUCT_ID_FOR_NOTIFICATION' on table …
```
=> [BM-257] :adhesive_bandage: notification.sql 위치 변경

build.gradle, src/main/java/com/saiko/bidmarket/chat/controller/ChatWebSocketController.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatPublishMessage.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatSendMessage.java, src/main/java/com/saiko/bidmarket/chat/entity/ChatMessage.java, src/main/java/com/saiko/bidmarket/chat/entity/ChatRoom.java, src/main/java/com/saiko/bidmarket/chat/service/ChatMessageService.java, src/main/java/com/saiko/bidmarket/chat/service/DefaultChatMessageService.java, src/main/java/com/saiko/bidmarket/chat/service/dto/ChatMessageCreateParam.java, src/main/java/com/saiko/bidmarket/common/config/WebSocketConfig.java, src/test/java/com/saiko/bidmarket/chat/controller/ChatWebSocketControllerTest.java, src/test/resources/application-ws_test.yaml
프론트의 stomp 클라이언트는 ws-stomp 의 엔드포인트로 http 요청을 통해 핸드셰이크를 하고 message/room/{채팅방 번호}, chat/room/{채팅방 번호} 로 각각 메시지 발행, 구독을 하게 됩니다.
- 웹소켓 테스트를 짜는데, WebMvcTest처럼 테스트 하고자 하는 기능(웹소켓)만 따로 빼서 테스트 할 수있는 기능이 없어서 SpringBootTest로 통합테스트를 진행해야 합니다. 통합테스트를 진행하면, Repository관련 의존성이 로드가 되어야되서 TestContainer를 로드할수 밖에 없게되는데 테스트 속도가 너무느립니다. 그래서 웹소켓 테스트만 h2 db로 진행하였습니다.
- 해당 테스트는 통합테스트이긴 하지만, repository 레이어 테스트하는것이 아니기 때문에 큰 문제는 없을것 같습니다.
- 웹소켓용 테스트 프로퍼티를 따로 만들었습니다(ws_test.yaml)
- 실패테스트를 위해서는 웹소켓 에러핸들러까지 구현해야하는데 PR이 너무 커지는것 같아 다음 PR에 올리겠습니다.
=> [BM-229] 웹소켓 설정 및 채팅 메시지 기능 구현

src/main/java/com/saiko/bidmarket/chat/controller/ChatWebSocketController.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatSendMessage.java, src/test/java/com/saiko/bidmarket/chat/controller/ChatWebSocketControllerTest.java
- 채팅 메시지가 유효하지 않은 데이터로 잘못전달된경우 어떤 채널로 에러를 보낼지, 혹은 서버 로그만찍을지 에 대한 논의를 프론트랑 해야할것 같습니다.
- 우선 핸들러구현을 통해 예외발생을 확인하는 정도로만 하고, 논의후에 예외처리를 세분화하겠습니다.
=> [BM-258] 웹소켓 예외 핸들러 구현

src/main/java/com/saiko/bidmarket/bidding/entity/Biddings.java, src/main/java/com/saiko/bidmarket/bidding/service/BiddingService.java, src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java, src/main/java/com/saiko/bidmarket/product/entity/Product.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/test/java/com/saiko/bidmarket/bidding/entity/BiddingsTest.java, src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java, src/test/java/com/saiko/bidmarket/product/entity/ProductTest.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
* 경매 종료 로직을 BiddingService와 ProductService에 걸쳐서 구현을 했었으나, 객체지향적이지 못한 느낌을 받아서 부족하지만 객체지향적으로 리팩토링을 해보았습니다.
* 수정된 사항
* Product 필드에 `List<Bidding> biddings` 을 추가함으로써 양방향 관계 설정
* `List<Bidding> biddings` 를 담은 Biddings 일급컬렉션 생성
* List<Bidding> biddings 리스트는 비즈니스 로직을 제공할 수 있는 방법은 없지만, 일급컬렉션 객체를 생성함으로써 내부에 낙찰자 선정과 낙찰값 선정에 대한 비즈니스 로직을 담았습니다.
=> [BM-222] 경매 종료 로직 리팩토링

src/main/java/com/saiko/bidmarket/common/entity/UnsignedLong.java, src/main/java/com/saiko/bidmarket/report/entity/Report.java, src/main/java/com/saiko/bidmarket/report/repository/ReportRepository.java, src/main/java/com/saiko/bidmarket/report/service/DefaultReportService.java, src/main/java/com/saiko/bidmarket/report/service/ReportService.java, src/main/java/com/saiko/bidmarket/report/service/dto/ReportCreateDto.java, src/main/java/com/saiko/bidmarket/user/entity/User.java, src/main/resources/sql/constraint.sql, src/test/java/com/saiko/bidmarket/report/service/DefaultReportServiceTest.java
- 중복 신고 방지 로직 추가
- 신고 레포지토리 구현
- 신고 서비스 구현 및 신고 기능 구현
- 신고 서비스 신고 기능 테스트 작성
- 중복 신고 방지를 서비스 레이어에서 우선적으로 확인하고 있으며, db에 제약조건으로 db에서도 방지되도록 하였습니다.
- 중복 신고 확인을 위해 신고자와 피신고자를 이용해 신고 조회를 추가하였습니다.
=> [BM-260] 신고하기 기능을 위한 신고 서비스, 레포 구현 및 테스트 작성

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/main/java/com/saiko/bidmarket/common/entity/BaseCreateResponse.java, src/main/java/com/saiko/bidmarket/common/exception/ExceptionController.java, src/main/java/com/saiko/bidmarket/report/controller/ReportApiController.java, src/main/java/com/saiko/bidmarket/report/controller/dto/ReportCreateRequest.java, src/main/java/com/saiko/bidmarket/report/controller/dto/ReportCreateResponse.java, src/test/java/com/saiko/bidmarket/report/controller/ReportApiControllerTest.java
- 신고하기 컨트롤러 생성
- 신고 생성 기능 구현
- 기본 생성 아이디 반환 객체 생성 및 상속
- 생성 후 id를 반환하는 작업이 반복적으로 이루어져서 생성된 아이디를 반환하는 기본 객체를 상속하여 적용해보았습니다.
=> [BM-255] 신고 컨트롤러 및 신고하기 기능 구현, 테스트 작성

src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/java/com/saiko/bidmarket/product/service/ProductService.java, src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
경매종료시 종료 대상 상품들에 대해 채팅방을 생성하는 로직을 작성하려고 경매 종료 로직을 확인하였는데, `executeClosingProduct` 메서드가 인자로 컬렉션을 받아 처리하다 보니, 호출된 메서드 내부에서 컬렉션을 풀어주는 for문이 불필요하게 추가됩니다. 가독성을 높이고자 다음과 같이 리팩토링 제안드립니다. @ecvheo1 
- 스트림을 통해 product 컬렉션을 넘기지 말고 product 단일 객체만 executeClosingProduct에 전달
=> [BM-268] executeClosingProduct 인자 변경(컬렉션 -> 단일 객체)

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/main/java/com/saiko/bidmarket/common/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/com/saiko/bidmarket/common/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/saiko/bidmarket/common/util/CookieUtils.java
기존에 하드코딩으로 되어있던 리다이렉트 url을 프론트에서 처음 요청시 redirect url로 리다이렉트 하도록 수정했습니다.
localhost:8080/oauth2/authorization/google?redirect_uri=http://localhost:3000/auth
이렇게 로그인 요청시 localhost:3000/auth로 리다이렉트 해줌
=> [BM-246] 로그인 요청 url의 리다이렉트 url로 로그인시 리다이렉트

src/main/java/com/saiko/bidmarket/bidding/repository/BiddingCustomRepository.java, src/main/java/com/saiko/bidmarket/bidding/repository/BiddingCustomRepositoryImpl.java, src/main/java/com/saiko/bidmarket/bidding/repository/dto/BiddingPriceFindingRepoDto.java, src/test/java/com/saiko/bidmarket/bidding/repository/BiddingRepositoryTest.java
- 비딩 금액 조회 기능 구현
- 함수명으로 쿼리를 생성할 경우 도메인 객체 조회 로직이 추가 되어서 Select Query가 2번 더 날라가게 됩니다.
- Select Query 없이 id 값으로 바로 조회하기 위해서 JpaQueryFactory 적용하였습니다.
=> [BM-284] Bidding Repository 비딩 금액 조회 기능 구현

src/main/java/com/saiko/bidmarket/notification/entity/Notification.java, src/main/java/com/saiko/bidmarket/notification/event/NotificationCreateHandler.java, src/main/resources/sql/notification/notification_schema.sql
* 아래 이미지와 같이 알림 타입과 알림 메세지를 동시에 가지고 있어야하기 때문에, 기존에 정의해두었던 enum 타입을 활용하여 필드를 수정하였습니다.
=> [BM-291] :adhesive_bandage: 알림 엔티티 필드 수정

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/main/java/com/saiko/bidmarket/product/Role.java, src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java, src/main/java/com/saiko/bidmarket/product/controller/dto/BiddingResultResponse.java, src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java, src/main/java/com/saiko/bidmarket/product/service/ProductService.java, src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
* 자세한 내용은 아래 노션 페이지 참고 하시면 됩니다.
* https://backend-devcourse.notion.site/FE-ff8a34c58c944ae5b573ac6e29503d2c
* 위 노션 페이지에서 응답 결과만 달라졌습니다.
```java
role : string, // 판매자 or 입찰자 (입찰한 적 없는 유저인 경우는 404)
biddingSucceed : boolean, // 입찰 성공 여부 
chatRoomId: number // 채팅방 아이디
```
* api 문서
https://www.notion.so/backend-devcourse/API-eaca9192734e4a868991939c21e04971?p=e2f4f25f934f4f22bc995c621ebd026c&pm=s
=> [BM-280] :sparkles: 비딩 결과 조회 controller 구현

src/main/java/com/saiko/bidmarket/notification/controller/NotificationApiController.java, src/main/java/com/saiko/bidmarket/notification/controller/dto/NotificationSelectRequest.java, src/main/java/com/saiko/bidmarket/notification/controller/dto/NotificationSelectResponse.java, src/main/java/com/saiko/bidmarket/notification/repository/dto/NotificationRepoDto.java, src/main/java/com/saiko/bidmarket/notification/service/DefaultNotificationService.java, src/main/java/com/saiko/bidmarket/notification/service/NotificationService.java, src/test/java/com/saiko/bidmarket/notification/controller/NotificationApiControllerTest.java
* 알림 전체 조회 API Controller 구현입니다.
* ResponseDto 생성을 위하여 넘겨받은 객체는 Repository 계층에서 생성된 DTO 입니다.
* Product와 Notification 데이터들을 섞어서 받아야하기 때문에 따로 구현하였습니다.
`Get api/v1/notifications?offset=&limit`
200 OK
```
[
{
"id": Number, // 알림 id
"productId": Number,
"title": String,
"thumbnailImage": String,
"type": String, // ex) 입찰 종료, 상품 댓글
"content": String, // ex) 아쉽게도 이번에는 낙찰받지 못하셨어요. :( 다음에 다신 도전해주세요.
"createdAt": Date, // 알림 생성 시간
"updatedAt": Date
},
{} // 유사 데이터 limit 개수만큼 반환
]	
```
=> [BM-220] 알림 전체 조회 API Controller 구현

src/main/java/com/saiko/bidmarket/chat/controller/ChatRoomApiController.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatRoomSelectRequest.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatRoomSelectResponse.java, src/main/java/com/saiko/bidmarket/chat/service/ChatRoomService.java, src/main/java/com/saiko/bidmarket/chat/service/DefaultChatRoomService.java, src/main/java/com/saiko/bidmarket/chat/service/dto/ChatRoomSelectParam.java, src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/test/java/com/saiko/bidmarket/chat/controller/ChatRoomApiControllerTest.java
- 사용자가 현재 활성화 되어있는 채팅방을 조회하는 API를 구현하였습니다.
- 무한스크롤 형식으로 offset, limit을 쿼리 파라미터에 포함하였습니다
- 인가되지 않은경우 302가 아닌 403 에러 응답을 주기 위해 AuthenticationEntryPoint를 추가하였습니다. [참고](https://www.notion.so/backend-devcourse/c0954a42b659425e89be36728b62ace4?v=fba9be0e1028483fbc485c2f50704501&p=693a914e65294b15ba4ca87d43f7e8fc&pm=s)
```
GET api/v1/charRooms?offset=&limit=
```
```json
response
[ {
"chatRoomId" : 1, //채팅방 번호
"productInfo" : { //상품 정보
"productId" : 1,
"thumbnailImg" : "https://test.img"
},
"opponentUserInfo" : { //상대방 유저 정보
"username" : "test",
"profileImg" : "test"
},
"lastMessage" : "test", //마지막 메시지 내용
"lastMessageDate" : "2022-08-09T18:33:17.76155" //마지막 메시지 보낸시간
} ]
```
=> [BM-289] 채팅방 조회 API 컨트롤러 구현

src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/main/java/com/saiko/bidmarket/user/service/UserService.java, src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
요즘 게을러져서 이게 이제야 올라오네요 죄송합니다
회원 탈퇴 api 컨트롤러 구현입니다.
다음 pr에서 서비스 레이어 구현을 올릴텐데 현재 제가 생각한 회원탈퇴 처리는 이렇습니다.
- User Entity의 username을 "Unknown"으로 변경 (이 닉네임은 사용하지 못하게 해야겠죠?)
- provider, providerId 는 null로 변경 -> 현재 NotNull 제약조건이 걸려있는데 해제해야할 것 같습니다.
- 프로필사진은 어떻게 할지 고민중
- 현재 제가 임시로 구현해둔 서비스에서는 해당 유저의 bidding 객체를 모두 삭제하도록 처리했습니다.  (경매에 영향을 주지 않기위해)
- 해당 유저의 게시물을 모두 finish 처리하도록 구현할 계획입니다.
- 별다른 조치를 취하지 않았습니다. 아마 Unknown의 댓글로 남아있을것 같습니다.
---
Product엔티티를 단순히 경매 종료 처리해도 될지 
아마 상품 검색이나 조회시 Unknown의 게시물로 남아있을것 같은데 
soft delete 로 컬럼을 하나 두어 조회하지 않게 처리할지 고민이네요
=> [BM-217] 회원탈퇴 api 컨트롤러 구현

src/main/java/com/saiko/bidmarket/common/config/WebSocketConfig.java
- stomp 웹소켓 연결 cors 제거하였습니다(프론트 로컬개발을 위해)
- 프론트 배포완료되면 추후에 추가하도록 하겠습니다.
=> [BM-316] :bug: stomp cors제거 (임시)

src/main/java/com/saiko/bidmarket/report/entity/Report.java, src/main/resources/sql/report/report_schema.sql
- 요구사항 변경에 따른 신고 객체 재정의
- AS-IS
- 신고하기 기능은 사용자가 사용자를 신고
- TO-BE
- 신고하기 기능은 사용자가 특정 게시물과 그 작성자를 신고
- 신고하기 기능은 사용자가 특정 댓글과 그 작성자를 신고
- 기존에는 유저를 직접 신고하는 식으로 구현하였으나 게시물이나 댓글을 신고하고 이를 각각 객체와 작성자에 대한 통합 신고 형태로 변환하였습니다.
- 게시물에 대한 신고와 댓글에 대한 신고는 일단 type이라는 필드를 만들어서 구분하고 typeId를 fk 없이 참고키처럼 사용하고자 합니다!
**신고 객체 변화가 발생하면 실제 DB에서 제약 조건에 걸려서 데이터 생성은 되지 않습니다! 테스트 코드는 mocking 되어 있어서 문제 없이 동작합니다. **
=> [BM-321] 신고 객체 재정의

src/main/resources/sql/constraint.sql, src/main/resources/sql/report/report_schema.sql
- type, type_id nullable로 변경
- type_id, type  index 추가
- type,type_id null인 경우는 비딩 종료 이후 채팅 과정에서 사용자를 직접 신고
- 이 경우에는 게시물이나 댓글이 아닌 사용자를 직접 신고하여 null이 될 수 있어서 not null을 삭제
- type_id, type index 추가하여 게시물이나 댓글에 대한 신고 조회 시 빠르게 조회
- type은 type_id에 비해 카디널리티가 낮아서 카디널리티가 높은 type_id부터 index 적용
=> [BM-321] type, typeId 관련 수정

src/main/java/com/saiko/bidmarket/report/entity/Report.java
- null 처리 누락 사항 추가 (builder 및 validate)
- type을 포함한 builder와 없는 builder를 구분할 수 있도록 메소드명을 재정의
- valiate 함수를 만들어 valition을 진행
=> [BM-321] type, typeId null 처리 수정

src/main/java/com/saiko/bidmarket/chat/controller/ChatMessageApiController.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatMessageSelectRequest.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatMessageSelectResponse.java, src/main/java/com/saiko/bidmarket/chat/service/ChatMessageService.java, src/main/java/com/saiko/bidmarket/chat/service/DefaultChatMessageService.java, src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java, src/test/java/com/saiko/bidmarket/chat/controller/ChatMessageApiControllerTest.java
채팅방에 접속하면 해당 채팅방의 채팅내역을 DB에서 불러오기 위한 api를 구현하였습니다.
```
header : 인증 토큰
$ http GET 'http://localhost:8080/api/v1/chatRooms/{채팅방 번호}/messages?offset={오프셋 시작}&limit={조회개수}
```
```json
[ {
"userId" : 1,
"content" : "test",
"createdAt" : "2022-08-12T15:35:08.693689"
} ]
```
=> [BM-290] 채팅 메시지 조회 api 컨트롤러 구현

src/main/java/com/saiko/bidmarket/notification/controller/NotificationApiController.java, src/main/java/com/saiko/bidmarket/notification/entity/Notification.java, src/main/java/com/saiko/bidmarket/notification/service/DefaultNotificationService.java, src/main/java/com/saiko/bidmarket/notification/service/NotificationService.java, src/test/java/com/saiko/bidmarket/notification/controller/NotificationApiControllerTest.java, src/test/java/com/saiko/bidmarket/notification/service/DefaultNotificationServiceTest.java
* 아래 이미지와 같이 알림을 확인하지 않은 것과 이미 확인한 알림을 구별하기 위해, 알림을 확인할 때 요청되는 API를 구현하였습니다.
```
Hibernate: 
select
notificati0_.id as id1_8_0_,
notificati0_.created_at as created_2_8_0_,
notificati0_.updated_at as updated_3_8_0_,
notificati0_.checked as checked4_8_0_,
notificati0_.product_id as product_6_8_0_,
notificati0_.type as type5_8_0_,
notificati0_.user_id as user_id7_8_0_ 
from
notification notificati0_ 
where
notificati0_.id=?
Hibernate: 
select
user0_.id as id1_12_0_,
user0_.created_at as created_2_12_0_,
user0_.updated_at as updated_3_12_0_,
user0_.group_id as group_id8_12_0_,
user0_.profile_image as profile_4_12_0_,
user0_.provider as provider5_12_0_,
user0_.provider_id as provider6_12_0_,
user0_.username as username7_12_0_,
group1_.id as id1_4_1_,
group1_.name as name2_4_1_ 
from
`user` …
```
=> [BM-327] 알림 확인 기능 구현

src/main/java/com/saiko/bidmarket/chat/entity/ChatRoom.java, src/main/java/com/saiko/bidmarket/chat/repository/ChatMessageCustomRepository.java, src/main/java/com/saiko/bidmarket/chat/repository/ChatMessageCustomRepositoryImpl.java, src/main/java/com/saiko/bidmarket/chat/service/DefaultChatMessageService.java, src/test/java/com/saiko/bidmarket/chat/repository/ChatMessageRepositoryTest.java, src/test/java/com/saiko/bidmarket/chat/service/DefaultChatMessageServiceTest.java
- 채팅방 메시지 조회를 위한 Service, Repository 메서드를 작성하였습니다
- 해당 채팅방에 속하지 않은 사용자가 조회하면 에러를 발생시키도록 하였습니다.
- 메시지는 최신순으로 조회됩니다.
```
GET http://localhost:8080/api/v1/chatRooms/2/messages?offset=0&limit=10
```
```
[
{
"userId": 1,
"content": "마지막 메세지",
"createdAt": "2022-08-10T13:13:54"
},
{
"userId": 3,
"content": "거래는 어떻게 할까요??",
"createdAt": "2022-08-10T13:13:45"
},
{
"userId": 1,
"content": "네! 개 맘에 듭니다.",
"createdAt": "2022-08-10T13:13:34"
},
{
"userId": 3,
"content": "네 물건 좋죠?",
"createdAt": "2022-08-10T13:13:25"
},
{
"userId": 1,
"content": "안녕하세요",
"createdAt": "2022-08-10T13:13:14"
},
{
"userId": 3,
"content": "안녕하세요",
"createdAt": "2022-08-10T13:13:13"
}
]
```
```
select
chatmessag0_.id as id1_1_,
chatmessag0_.created_at as created_2_1_,
chatmessag0_.updated_at as updated_3_1_, …
```
=> [BM-294] 채팅방 메시지 조회 Service, Repository 메서드 작성

src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatMessageSelectResponse.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatPublishMessage.java, src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatUserInfo.java, src/main/java/com/saiko/bidmarket/chat/repository/ChatMessageCustomRepositoryImpl.java, src/test/java/com/saiko/bidmarket/chat/controller/ChatMessageApiControllerTest.java, src/test/java/com/saiko/bidmarket/chat/controller/ChatWebSocketControllerTest.java, src/test/java/com/saiko/bidmarket/chat/service/DefaultChatMessageServiceTest.java
- 프론트 요청에 따라 채팅 메시지를 보낸 사용자에 대한 정보를 구체화하였습니다.
- 웹소켓응답, HTTP API 응답 두가지에 같은 변경사항을 적용하였습니다.
```
[ {
"userInfo" : {
"userId" : 1,
"username" : "test",
"profileImage" : "test"
},
"content" : "test",
"createdAt" : "2022-08-13T21:19:21.166962"
} ]
```
```
{
"userInfo" : {
"userId" : 1,
"username" : "test",
"profileImage" : "test"
},
"content" : "test",
"createdAt" : "2022-08-13T21:19:21.166962"
}
```
=> [BM-345] 채팅 메시지 관련 응답필드 변경

src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectResponse.java, src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
* 댓글 신고를 위해 댓글 전체 조회 응답에 댓글 아이디를 추가했습니다.
* postman 테스트
=> [BM-336] :sparkles: 댓글 전체 조회 응답에 댓글 아이디 추가

src/main/java/com/saiko/bidmarket/heart/repository/HeartCustomRepository.java, src/main/java/com/saiko/bidmarket/heart/repository/HeartCustomRepositoryImpl.java, src/main/java/com/saiko/bidmarket/heart/repository/HeartRepository.java, src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java, src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectResponse.java, src/main/java/com/saiko/bidmarket/user/controller/dto/UserHeartSelectRequest.java, src/main/java/com/saiko/bidmarket/user/controller/dto/UserHeartSelectResponse.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/main/java/com/saiko/bidmarket/user/service/UserService.java, src/test/java/com/saiko/bidmarket/heart/repository/HeartRepositoryTest.java, src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java, src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
* 회원 찜한 상품 조회를 구현하였습니다.
* UserBiddingSelectResponse, UserProductSelectResponse, UserHeartSelectResponse 와 UserBiddingSelectRequest, UserProductSelectRequest, UserHeartSelectRequest 필드값이 똑같은 객체가 있어서 나중에 리팩토링을 해야할 거 같습니다.
=> [BM-215] 회원 찜한 상품 조회

src/main/java/com/saiko/bidmarket/heart/repository/HeartRepository.java, src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java, src/main/java/com/saiko/bidmarket/user/controller/dto/UserHeartCheckResponse.java, src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java, src/main/java/com/saiko/bidmarket/user/service/UserService.java, src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java, src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java
- 유저가 헤딩 싱픔에 찜했는지 확인하는 api입니다.
- 상품 상세정보에 응답필드 추가보다 api 하나 파는게 구현상 더 쉬울것같다고 해서 구현했습니다.
- 사진에 Request Body는 무시해도됩니다
=> [BM-349] 상품 찜여부 api 구현 컨트롤러 + 서비스
