prgrms-web-devcourse/Team-Saiko-BidMarket-BE

.gitignore
.husky/prepare-commit-msg
package-lock.json
package.json

리포지토리 폴더에서 `npm install husky jira-prepare-commit-msg --save-dev && npx husky install` 명령어만 입력해 주시면 다음과 같이 브랜치의 티켓 번호에 따라 커밋 메시지가 자동화 됩니다.

[BM-98] :construction_worker: husky 커밋메시지 지라티켓 자동화

---

build.gradle
src/main/java/com/saiko/bidmarket/product/entity/Image.java
src/main/java/com/saiko/bidmarket/product/entity/Product.java

* 잘못 import한 라이브러리를 변경하였습니다.
* com.sun.istack.NotNull ->  org.springframework.boot:spring-boot-starter-validation

[BM-64] 잘못 import 된 @NotNull 라이브러리 변경

---

.gitignore

- 개발용 DB 서버를 로컬에서 실행하는 것 관련하여 환경을 동일하게 유지할 수 있도록 Container 도입
- 관련 스크립트는 따로 공유
- root 폴더에서 infra 폴더로 놓고 사용하시면 될 것 같습니다.
- 해당 폴더 git ignore 추가하였습니다.

[BM-114] :see_no_evil: 컨테이너 스크립트 폴더 git ignore 추가

---

.github/workflows/unit-test.yml
codecov.yml

codecov.yml 파일이 빠져있어 추가하였습니다.
codecov ci에서 대상 브랜치 목록중 develop 브랜치를 제거하였습니다.

[BM-97]  CI codecov 버그 수정

---

src/main/java/com/saiko/bidmarket/common/entity/BaseTime.java
src/main/java/com/saiko/bidmarket/common/exception/ExceptionController.java
src/main/java/com/saiko/bidmarket/product/Repository/ProductRepository.java
src/main/java/com/saiko/bidmarket/product/controller/ProductController.java
src/main/java/com/saiko/bidmarket/product/controller/ProductDetailResponse.java
src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/main/java/com/saiko/bidmarket/product/service/ProductService.java
src/test/java/com/saiko/bidmarket/product/controller/ProductControllerTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

```
bidmarket
│  Application.java
│  
├─common
│  ├─entity
│  │      BaseTime.java
│  │      
│  └─exception
│          ExceptionController.java
│          NotFoundException.java
│          
├─product
│  │  Category.java
│  │  
│  ├─controller
│  │      ProductController.java
│  │      ProductDetailResponse.java
│  │      
│  ├─entity
│  │      Image.java
│  │      Product.java
│  │      
│  ├─Repository
│  │      ProductRepository.java
│  │      
│  └─service
│          DefaultProductService.java
│          ProductService.java
│
└─user
└─entity
Group.java
GroupPermission.java
Permission.java
User.java
```
package들이 제대로 구성되기 전이라  전체적인 폴더 구조를 다음과 같이 잡았습니다.
1. common package의 exception
- 공통적으로 사용되는 NotFoundException 정의 - 특정 값을 통한 자원 조회 시 해당 자원을 찾지 못하였을 때 사용
- ExceptionController 정의 - …

[BM-53] 상품 상세조회 기능 구현

---

.github/CODEOWNERS

[BM-133] :construction_worker: CODEOWNERS 추가

---

src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/main/java/com/saiko/bidmarket/user/service/UserService.java
src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java

UserService에 findById 메서드를 추가했습니다.
컨트롤러로부터 id를 받아 유저객체를 가져올때 사용하면 될것 같습니다.

[BM-134] UserService findById 추가

---

.github/workflows/deploy.yml
appspec.yml
build.gradle
scripts/gh_deploy.sh
src/main/resources/application.yaml

- 배포관련 설정입니다.
- release 브렌치에 push될때 배포가 진행되도록 설정하였습니다.
- 민감한 정보들은 gitaction을 통해 동적으로 변수값 주입하도록 변경하였습니다. 
- 로컬에서 빌드하기위해서 슬랙에 공유드린 환경변수를 채워주시길 바랍니다.

[BM-141] :construction_worker: 배포 관련 설정

---

.github/workflows/deploy.yml
appspec.yml
build.gradle
scripts/gh_deploy.sh
src/main/resources/application.yaml

- 배포과정에서 오류를 발생시킨 오타들을 수정하였습니다.

[BM-141] :bug: 배포 관련 버그 수정

---

src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserUpdateRequest.java
src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/main/java/com/saiko/bidmarket/user/service/UserService.java
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java

회원 정보 수정 Controller 메서드 구현입니다.
유저 이름, 이미지를 변경할 수 있습니다.
감사합니다.
아 이미지 validation은 어떤걸 검사하면 좋을까요??

[BM-142] 회원 정보 수정 Controller 메서드 구현

---

src/main/java/com/saiko/bidmarket/common/exception/ExceptionController.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java

productService에 @Transactional 안붙어있길래 이번 PR에 고쳐놨습니다.
---
예외 컨트롤러에 예외 추가했습니다. 감사합니다.
`MethodArgumentNotValidException` : @RequestBody @Valid 어노테이션으로 dto 유효성 검사시 발생하는 예외
`MethodArgumentTypeMismatchException` :  @RequestBody @Valid 어노테이션으로 dto 유효성 검사시 필드 타입이 다를 경우
`NumberFormatException` :  @ModelAttribute @Valid 어노테이션으로 유효성 검사시 숫자 타입에 문자를 넣을 경우
`ConversionFailedException` :  @ModelAttribute @Valid 어노테이션으로 유효성 검사시 @Positive 에 음수가 들어갈 경우
`BindException` :  @ModelAttribute @Valid 어노테이션으로 유효성 검사시 바인딩 실패할 경우
**특이사항 `BindException` 을 controller advice에서 잡을때**
---
`import org.springframework.validation.BindException;` 요거 써야됨
`import java.net.BindException`  이거로 1시간 반 날림
`RuntimeException` 
`Exception` 예상 못한 예외 핸들링

[BM-88]  ExceptionController exception 추가

---

src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java
src/main/java/com/saiko/bidmarket/product/controller/ProductDetailResponse.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductApiService.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/main/java/com/saiko/bidmarket/product/service/ProductApiService.java
src/main/java/com/saiko/bidmarket/product/service/ProductService.java
src/main/resources/application.yaml
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductApiServiceTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

- 구두로 설명드린대로 서비스 클래스를 화면용 서비스 (~ApiService), 비즈니스 로직용 서비스(~Service) 로 분리하여 리팩토링 하였습니다.

[BM-153] 화면용 서비스, 비즈니스 로직용 서비스 분리

---

src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java

* ProductCustomRepository 테스트 추가하였습니다.
* 실행되는 쿼리는 아래와 같습니다.
```java
Hibernate: 
select
product0_.id as id1_4_,
product0_.created_at as created_2_4_,
product0_.updated_at as updated_3_4_,
product0_.category as category4_4_,
product0_.description as descript5_4_,
product0_.expire_at as expire_a6_4_,
product0_.location as location7_4_,
product0_.minimum_price as minimum_8_4_,
product0_.thumbnail_image as thumbnai9_4_,
product0_.title as title10_4_,
product0_.user_id as user_id11_4_ 
from
order by
```

[BM-131] :white_check_mark: ProductCustomRepository 테스트 추가

---

build.gradle

[BM-178] :heavy_plus_sign: lombok 의존성 추가

---

build.gradle
src/main/java/com/saiko/bidmarket/Application.java
src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java
src/main/java/com/saiko/bidmarket/common/jwt/JwtAuthenticationFilter.java
src/main/java/com/saiko/bidmarket/common/oauth2/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/saiko/bidmarket/user/entity/Permission.java
src/test/java/com/saiko/bidmarket/product/SchedulerTest.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java

* 외부 라이브러리 (awaitility) 를 사용하지 않고 테스트 할 수 있는 방법이 있긴 한데 이 방법은 프로덕션 코드에 호출 횟수를 세는 코드가 추가 되기 때문에 외부 라이브러리를 추가해서 테스트 했습니다.
* 참고: https://www.baeldung.com/spring-testing-scheduled-annotation

[BM-163] :sparkles: 배치 처리 기능 구현

---

src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/resources/sql/product/product_schema.sql

* Product Getter 와 Builder 애노테이션 적용
* 경매 진행중인지 종료되었는지 확인하는 필드값 추가
* progressed = true : 경매 진행중
* progressed = false : 경매 종료

[BM-67] Product 엔티티 Lombok 적용 & progressed 필드 추가

---

src/main/java/com/saiko/bidmarket/common/oauth2/OAuth2AuthenticationSuccessHandler.java

레이님에게 질문해본 결과 일단 지금은 쿼리스트링으로 받고(실제로도 이렇게 받는 서비스도 몇몇 있다고 하심) 추후 변경하는걸로 (쿠키 or get) 변경은 무조건 할겁니다!

[BM-174] :recycle: login token queryString 으로 변경 (추후 리펙토링)

---

src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepository.java
src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
src/main/java/com/saiko/bidmarket/product/repository/dto/UserProductSelectQueryParameter.java
src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/main/java/com/saiko/bidmarket/user/service/dto/UserProductSelectQueryParameter.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java

- 유저가 판매한 상품을 조회하는 Service, Repository 메서드를 구현하였습니다
- Service 에서 Repository 로 `UserProductSelectQueryParameter` DTO를 통해 데이터를 전달하도록 구현하였습니다.
-  DTO 위치는 ProductRepository가 있는 곳에 두었습니다.
- 쿼리는 다음과 같습니다.
```
Hibernate: 
select
product0_.id as id1_7_,
product0_.created_at as created_2_7_,
product0_.updated_at as updated_3_7_,
product0_.category as category4_7_,
product0_.description as descript5_7_,
product0_.expire_at as expire_a6_7_,
product0_.location as location7_7_,
product0_.minimum_price as minimum_8_7_,
product0_.progressed as progress9_7_,
product0_.thumbnail_image as thumbna10_7_,
product0_.title as title11_7_,
product0_.user_id as user_id12_7_ 
from
inner join
`user` user1_ 
on product0_.user_id=user1_.id 
where
user1_.id=? 
order by …
```

[BM-182] 유저 판매한 상품 조회 Service, Repository 메서드 구현

---

src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java

* progressed : 경매가 진행중인지 아닌지를 판단하는 필드값의 초기값 변경, false -> true 
죄송합니다..

[BM-194] 경매 종료 여부 필드 수정

---

scripts/gh_deploy.sh
src/main/resources/application.yaml

[BM-196] :recycle: 8080으로 포트 변경

---

src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/resources/sql/product/product_schema.sql
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java

* 프론트 요청으로 상품 등록 title 길이 제한 수정했습니다. (16 -> 32)

[BM-202] :recycle: 상품 등록 title 길이 제한 수정 (16 -> 32)

---

src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java
src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java

- 비딩 시에 자신의 상품인지 검증하는 로직 추가 및 테스트 구현

[BM-206] 비딩 시 자신의 상품 검증 로직 및 테스트 구현

---

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java

전체 조회에서 스크롤로 다시 요청시 cors에러가 나서 열어봤습니다.

[BM-208] :sparkles: cors 열어주기

---

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java

[BM-208] :recycle: cors 코드 수정정

---

src/main/resources/sql/constraint.sql

[BM-211] :sparkles: username unique 제거

---

src/main/java/com/saiko/bidmarket/product/controller/dto/ProductCreateRequest.java
src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java

* 검색 기능에 "제목 키워드로 검색" 추가했습니다.
* 제목 키워드가 없다면 전체 제목 검색합니다.
* 제목 키워드가 있다면 해당 키워드를 가진 상품만 검색합니다.
1. 제목 키워드 없이 검색
```java
Hibernate: 
select
product0_.id as id1_7_,
product0_.created_at as created_2_7_,
product0_.updated_at as updated_3_7_,
product0_.category as category4_7_,
product0_.description as descript5_7_,
product0_.expire_at as expire_a6_7_,
product0_.location as location7_7_,
product0_.minimum_price as minimum_8_7_,
product0_.progressed as progress9_7_,
product0_.thumbnail_image as thumbna10_7_,
product0_.title as title11_7_,
product0_.winning_price as winning12_7_,
product0_.user_id as user_id13_7_ 
from
where
product0_.progressed=? 
order by
```
2. 제목 키워드와 함께 검색
```java
Hibernate: 
select
product0_.id as id1_7_, …
```

[BM-228] :sparkles: 키워드 검색 구현

---

src/main/java/com/saiko/bidmarket/product/controller/dto/ProductDetailResponse.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserSelectResponse.java
src/test/java/com/saiko/bidmarket/common/util/IdEncoderTest.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java

- encoded Id를 모두 걷어내고 id로 변환
- encoder와 test는 그대로 유지(test disabled 처리)

[BM-240] encodedId -> userId로 변환

---

src/main/java/com/saiko/bidmarket/user/controller/dto/UserSelectResponse.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserUpdateRequest.java
src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java

유저 프로필 이미지 변수명을 통일했습니다.
thumbnailImg -> profileImage
profileImageUrl -> profileImage

[BM-247] 유저 프로필 이미지 변수명 통일 

---

src/main/java/com/saiko/bidmarket/product/Category.java
src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java

* 기존에는 카테고리 정보를 넘겨주지 않을시에 전체 조회였음
* category=ALL로 넘겨주면 전체 조회 하도록 추가 구현

[BM-253] :sparkles: 상품 검색 전체 조회시 카테고리 ALL 처리 하도록 수정

---

src/main/java/com/saiko/bidmarket/bidding/controller/BiddingApiController.java
src/main/java/com/saiko/bidmarket/comment/controller/CommentApiController.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentCreateRequest.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentCreateResponse.java
src/main/java/com/saiko/bidmarket/comment/service/CommentService.java
src/main/java/com/saiko/bidmarket/comment/service/DefaultCommentService.java
src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java
src/test/java/com/saiko/bidmarket/bidding/controller/BiddingApiControllerTest.java
src/test/java/com/saiko/bidmarket/bidding/controller/BiddingControllerTest.java
src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java

* 댓글 생성 controller 구현
* BiddingController -> BiddingApiController

[BM-249] :sparkles: 댓글 생성 controller 구현

---

src/main/java/com/saiko/bidmarket/comment/entity/Comment.java
src/main/java/com/saiko/bidmarket/comment/repository/CommentRepository.java
src/main/java/com/saiko/bidmarket/comment/service/DefaultCommentService.java
src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java

* 댓글 생성 service, repository 구현하였습니다.
* 다음으로 댓글 조회 개발하겠습니다.

[BM-250] :sparkles: 댓글 생성 service, repository 구현

---

src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatPublishMessage.java
src/main/java/com/saiko/bidmarket/chat/repository/ChatMessageRepository.java
src/main/java/com/saiko/bidmarket/chat/repository/ChatRoomRepository.java
src/main/java/com/saiko/bidmarket/chat/service/DefaultChatMessageService.java
src/test/java/com/saiko/bidmarket/chat/service/DefaultChatMessageServiceTest.java

- 웹소켓으로 채팅 메시지를 받게 되면, 해당 내용으로 채팅 메시지를 생성하여 DB에 저장하는 기능을 구현하였습니다.

[BM-265] 채팅 메시지 생성기능 구현

---

src/main/java/com/saiko/bidmarket/report/service/DefaultReportService.java
src/main/java/com/saiko/bidmarket/report/service/dto/ReportCreateDto.java
src/test/java/com/saiko/bidmarket/report/service/DefaultReportServiceTest.java

- 신호 하기 요청자와 신고 데이터상 신고자에 대한 검증 로직 추가

[BM-260] 신고 서비스 신고하기 - 요청자와 신고자 검증 추가

---

src/main/java/com/saiko/bidmarket/bidding/entity/Bidding.java

- bidding과 User, Product의 Fetch Type 수정 (EAGER -> LAZY)

[BM-279] bidding 객체 Fetch Type 수정

---

src/main/java/com/saiko/bidmarket/bidding/respository/BiddingCustomRepositoryImpl.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectRequest.java
src/main/java/com/saiko/bidmarket/comment/repository/CommentCustomRepositoryImpl.java
src/main/java/com/saiko/bidmarket/common/Sort.java
src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
src/main/java/com/saiko/bidmarket/product/repository/dto/UserProductSelectQueryParameter.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectRequest.java
src/test/java/com/saiko/bidmarket/bidding/repository/BiddingRepositoryTest.java
src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
src/test/java/com/saiko/bidmarket/comment/repository/CommentRepositoryTest.java
src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java

* Sort 가 여러 도메인에서 사용되는데 product  패키지에 있는게 이상한거 같아서 패키지 common으로 변경했습니다.

[BM-269] :recycle: Sort 패키지 변경

---

src/main/java/com/saiko/bidmarket/notification/NotificationType.java

* 아래 사진과 같이 알림 타입별 메세지 내용을 수정하였습니다.

[BM-288] :beers: 알림 메세지 내용 수정

---

src/main/java/com/saiko/bidmarket/bidding/service/BiddingService.java
src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java
src/main/java/com/saiko/bidmarket/bidding/service/dto/BiddingPriceFindingDto.java
src/test/java/com/saiko/bidmarket/bidding/service/DefaultBiddingServiceTest.java

- 비딩 서비스의 비딩 금액 조회 기능 구현
- 비딩 서비스 테스트의 비딩 금액 조회 기능 테스트 작성

[BM-282] 비딩 서비스 비딩 금액 조회 기능 및 테스트 구현

---

src/main/java/com/saiko/bidmarket/bidding/controller/BiddingApiController.java
src/main/java/com/saiko/bidmarket/bidding/controller/dto/BiddingPriceResponse.java
src/main/java/com/saiko/bidmarket/bidding/entity/BiddingPrice.java
src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java
src/test/java/com/saiko/bidmarket/bidding/controller/BiddingApiControllerTest.java

- 비딩 컨트롤러 비딩 금액 조회 기능 구현
- 비딩 컨트롤러 테스트 비딩 금액 조회 기능 테스트

[BM-283] 비딩 컨트롤러 비딩 금액 조회 기능 구현

---

src/main/java/com/saiko/bidmarket/chat/repository/ChatRoomRepository.java
src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/java/com/saiko/bidmarket/product/repository/ProductRepository.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/main/java/com/saiko/bidmarket/user/entity/User.java
src/test/java/com/saiko/bidmarket/chat/repository/ChatRoomRepositoryTest.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

* 판매자 & 낙찰 성공 
* 판매자 & 낙찰 실패
* 입찰자 & 낙찰 성공
* 입찰자 & 낙찰 실패
* 입찰하지 않은 유저

[BM-281] :sparkles: 비딩 결과 조회 service, repository 구현

---

src/main/java/com/saiko/bidmarket/common/config/WebSecurityConfig.java
src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java

[BM-298] :recycle: url 수정

---

src/main/java/com/saiko/bidmarket/notification/controller/dto/NotificationSelectRequest.java
src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
src/main/java/com/saiko/bidmarket/product/repository/dto/UserProductSelectQueryParameter.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectRequest.java

[BM-293] :recycle: offset long 타입으로 변경

---

src/main/java/com/saiko/bidmarket/product/controller/dto/ProductCreateRequest.java
src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/resources/sql/product/product_schema.sql
src/test/java/com/saiko/bidmarket/bidding/repository/BiddingRepositoryTest.java
src/test/java/com/saiko/bidmarket/comment/repository/CommentRepositoryTest.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
src/test/java/com/saiko/bidmarket/user/repository/UserRepositoryTest.java

* "상품 등록에서 상품 이미지가 반드시 한 장 이상 들어와야 한다" 는 제약조건을 추가했습니다.

[BM-292] :recycle: 상품 등록 이미지 제약 조건 추가

---

src/main/resources/application.yaml

[BM-308] :adhesive_bandage: heart schema 위치 변경

---

src/main/java/com/saiko/bidmarket/product/controller/dto/ProductCreateRequest.java
src/main/java/com/saiko/bidmarket/product/controller/dto/ProductCreateResponse.java
src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/main/java/com/saiko/bidmarket/product/service/ProductService.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

* 롬복 적용
* Product 엔티티 @EqualsAndHashCode 수정 -> 관련 내용: https://www.notion.so/backend-devcourse/c0954a42b659425e89be36728b62ace4?v=fba9be0e1028483fbc485c2f50704501&p=2dbee0d27b314529a5f8e302af4b5a3e&pm=s
* 팩토리 메서드 적용
* 조회 서비스 메서드에 @Transactional(readonly = true) 사용

[BM-301] :recycle: 상품 생성 api 리팩토링

---

src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectRequest.java
src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectResponse.java
src/main/java/com/saiko/bidmarket/product/repository/ProductCustomRepositoryImpl.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/repository/ProductRepositoryTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

[BM-307] :recycle: 상품 전체 조회 api 리팩토링

---

src/main/java/com/saiko/bidmarket/product/entity/Product.java

비딩 입찰 가격순 내림차순 정렬 후 낙찰자 선정 로직 추가

[BM-310] :adhesive_bandage: 낙찰자 선정 수정

---

src/main/java/com/saiko/bidmarket/common/entity/BaseTime.java

[BM-314] :bug: updatedAt 어노테이션 수정

---

src/main/java/com/saiko/bidmarket/comment/controller/CommentApiController.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentCreateRequest.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentCreateResponse.java
src/main/java/com/saiko/bidmarket/comment/entity/Comment.java
src/main/java/com/saiko/bidmarket/comment/service/CommentService.java
src/main/java/com/saiko/bidmarket/comment/service/DefaultCommentService.java
src/main/java/com/saiko/bidmarket/product/controller/ProductApiController.java
src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java

* 롬복 적용
* 테스트 리팩토링
* UnsignedLong 제거
* 팩토리 메서드 적용
* 코드 포맷팅
* ProductApiController 롬복 적용

[BM-309] :recycle: 댓글 생성 API 리팩토링

---

src/main/java/com/saiko/bidmarket/notification/controller/dto/NotificationSelectResponse.java
src/main/java/com/saiko/bidmarket/notification/entity/Notification.java
src/main/java/com/saiko/bidmarket/notification/repository/NotificationCustomRepositoryImpl.java
src/main/java/com/saiko/bidmarket/notification/repository/dto/NotificationRepoDto.java
src/main/resources/sql/notification/notification_schema.sql
src/test/java/com/saiko/bidmarket/notification/controller/NotificationApiControllerTest.java
src/test/java/com/saiko/bidmarket/notification/repository/NotificationRepositoryTest.java
src/test/java/com/saiko/bidmarket/notification/service/DefaultNotificationServiceTest.java

* 유저가 알림을 조회했는지 안했는지 확인하는 boolean 타입의 필드를 추가하였습니다.
* read 가 mysql 예약어라서 checked 로 하였습니다.

[BM-324] 알림 전체 조회 반환값 추가

---

src/main/java/com/saiko/bidmarket/comment/controller/CommentApiController.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectRequest.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectResponse.java
src/main/java/com/saiko/bidmarket/comment/repository/CommentCustomRepositoryImpl.java
src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
src/test/java/com/saiko/bidmarket/comment/repository/CommentRepositoryTest.java
src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java

* 댓글 조회 리팩토링 했습니다.
* UnsignedLong 제거
* 테스트 코드 리팩토링
* 포맷팅
* 롬복 적용

[BM-322] :recycle: 댓글 조회 리팩토링

---

src/main/java/com/saiko/bidmarket/Application.java

[BM-330] :construction_worker: 어플리케이션 시간 동기화

---

scripts/gh_deploy.sh

[BM-330] :construction_worker: Application 시간 동기화 (단 1줄)

---

src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentCreateRequest.java
src/main/java/com/saiko/bidmarket/comment/controller/dto/CommentSelectRequest.java
src/main/java/com/saiko/bidmarket/comment/service/DefaultCommentService.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/test/java/com/saiko/bidmarket/comment/controller/CommentApiControllerTest.java
src/test/java/com/saiko/bidmarket/comment/service/DefaultCommentServiceTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

* 아까 pr 올린게 문제가 생겨서 다시 올립니다!
* 방금 어푸르브 찍어주신분들은 어푸르브만 찍어주시면 될거 같습니다!

[BM-331] :recycle: 상품 생성, 상품 조회, 상품 검색, 댓글 등록, 댓글 조회 id 검증 로직 제거

---

src/main/java/com/saiko/bidmarket/chat/service/ChatRoomService.java
src/main/java/com/saiko/bidmarket/chat/service/DefaultChatRoomService.java
src/main/java/com/saiko/bidmarket/common/config/ScheduledConfig.java
src/test/java/com/saiko/bidmarket/chat/service/DefaultChatRoomServiceTest.java
src/test/java/com/saiko/bidmarket/product/SchedulerTest.java

- 채팅방 생성 스케줄러에 연동하였습니다
- 비딩 종료시 위너가 있는 프로덕트에 대해 채팅방을 생성

[BM-312] :sparkles: 채팅방 생성 스케줄러 연동

---

src/main/java/com/saiko/bidmarket/product/controller/dto/BiddingResultResponse.java
src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java
src/test/java/com/saiko/bidmarket/product/service/DefaultProductServiceTest.java

* 아까 올렸다가 close 한 pr 입니다..
* 아까 해주신 분들은 어푸르브 바로 찍어주셔도 됩니다!!!!🙇🏻‍♀️ 
* close 한 pr
https://github.com/prgrms-web-devcourse/Team-Saiko-BidMarket-BE/pull/169

[BM-335] :sparkles: 낙찰 결과 확인 api 응답에 낙찰 금액 추가

---

src/main/java/com/saiko/bidmarket/heart/entity/Heart.java
src/main/java/com/saiko/bidmarket/heart/repository/HeartRepository.java
src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java
src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/main/java/com/saiko/bidmarket/user/service/UserService.java
src/main/resources/sql/heart/heart_schema.sql
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java
src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java

* 레이님의 피드백을 토대로, 양방향 연관관계를 끊고 Heart 엔티티를 구현하였습니다.
* Heart 엔티티에 대해서 추후 리팩토링할 예정입니다.

[BM-337] 찜하기 찜 취소하기 구현

---

src/main/java/com/saiko/bidmarket/chat/controller/dto/ChatPublishMessage.java
src/test/java/com/saiko/bidmarket/chat/controller/ChatWebSocketControllerTest.java

[BM-345] :adhesive_bandage: 필드명 수정

---

src/main/java/com/saiko/bidmarket/product/controller/dto/ProductSelectResponse.java
src/main/java/com/saiko/bidmarket/product/entity/Product.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java

- @Formula 어노테이션으로 product 필드에 찜 개수 필드를 추가했습니다. 
- DB에는 저장되지 않습니다.

[BM-347] 상품 전체 조회 응답에 찜개수 추가

---

src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java
src/main/java/com/saiko/bidmarket/user/controller/UserApiController.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectRequest.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectResponse.java
src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/test/java/com/saiko/bidmarket/product/controller/ProductApiControllerTest.java

* 롬복 적용
* 코드 포맷팅
* 트랜잭션 어노테이션 적용

[BM-323] :recycle: 입찰한 상품 조회 리팩토링

---

src/main/java/com/saiko/bidmarket/bidding/controller/BiddingApiController.java
src/main/java/com/saiko/bidmarket/bidding/service/DefaultBiddingService.java

- 비딩 금액 조회 핫 픽스
- 비딩 금액 조회 서비스에서 인자가 반대로 됨.

[BM-354] 비딩 금액 조회 인자 수정

---

src/main/java/com/saiko/bidmarket/notification/controller/NotificationApiController.java
src/main/java/com/saiko/bidmarket/notification/event/NotificationCreateHandler.java
src/main/java/com/saiko/bidmarket/notification/repository/NotificationCustomRepository.java
src/main/java/com/saiko/bidmarket/notification/repository/NotificationCustomRepositoryImpl.java
src/main/java/com/saiko/bidmarket/notification/repository/dto/NotificationRepoDto.java
src/main/java/com/saiko/bidmarket/notification/service/DefaultNotificationService.java
src/main/java/com/saiko/bidmarket/notification/service/NotificationService.java
src/test/java/com/saiko/bidmarket/notification/controller/NotificationApiControllerTest.java
src/test/java/com/saiko/bidmarket/notification/repository/NotificationRepositoryTest.java
src/test/java/com/saiko/bidmarket/notification/service/DefaultNotificationServiceTest.java

* id 양수 확인 삭제 및 관련 테스트 삭제
* 코드 컨벤션 포맷팅 적용
* UnsignedLong type을 primitive long type으로 변환
* 테스트 리팩토링

[BM-356] 알림 도메인 리팩토링

---

src/main/java/com/saiko/bidmarket/user/controller/dto/UserBiddingSelectResponse.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserHeartSelectResponse.java
src/main/java/com/saiko/bidmarket/user/controller/dto/UserProductSelectResponse.java
src/test/java/com/saiko/bidmarket/user/controller/UserApiControllerTest.java

[BM-358] :adhesive_bandage: heartCount응답필드 추가

---

src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java

[BM-364] :bug: Transactional 애노테이션 추가

---

README.md

[BM-340] 리드미 작성

---

src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java

[BM-367] :bug: 더티체킹 안되는거 픽스

---

src/main/java/com/saiko/bidmarket/product/service/DefaultProductService.java

알림 이벤트 객체 생성할 때 하나를 빼먹었습니다.
수정 완료

[BM-368] :bug: builder 수정

---

src/main/java/com/saiko/bidmarket/report/service/DefaultReportService.java
src/main/java/com/saiko/bidmarket/report/service/ReportValidator.java
src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForComment.java
src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForProduct.java
src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForUser.java
src/main/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteStrategy.java
src/test/java/com/saiko/bidmarket/report/service/ReportValidatorTest.java
src/test/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForCommentTest.java
src/test/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForProductTest.java
src/test/java/com/saiko/bidmarket/report/service/strategy/ReportExecuteForUserTest.java

- 기존 try ~ catch를 통해서 제어하던 객체의 작성자 신고 요청 로직을 boolean 반환으로 리팩토링

[BM-319] validator 응답 타입 변환 및 리팩토링

---

src/main/java/com/saiko/bidmarket/user/entity/User.java
src/main/java/com/saiko/bidmarket/user/service/DefaultUserService.java
src/main/java/com/saiko/bidmarket/user/service/UserService.java
src/test/java/com/saiko/bidmarket/user/service/DefaultUserServiceTest.java

복잡한 try-catch문으로 되어있던 join메서드를 개선하였습니다.
기존
```
@Override
@Transactional
public User join(OAuth2User oAuth2User, String authorizedClientRegistrationId) {
Assert.notNull(oAuth2User, "OAuth2User must be provided");
Assert.hasText(authorizedClientRegistrationId,
"AuthorizedClientRegistrationId must be provided");
String providerId = oAuth2User.getName();
try {
User user = findByProviderAndProviderId(authorizedClientRegistrationId, providerId);
log.warn("Already exists: {} for (provider: {}, providerId: {})", user,
authorizedClientRegistrationId, providerId);
return user;
} catch (NotFoundException e) {
Map<String, Object> attributes = oAuth2User.getAttributes();
String username = (String)attributes.get("name");
String profileImage = (String)attributes.get("picture");
log.info("username : {} …
```

[BM-381] 회원가입 로직 리팩토링

---

src/main/java/com/saiko/bidmarket/common/jwt/Jwt.java

- 리팩토링하다 실수로 삭제된 부분(토큰에서 권한 가져오는 로직)이 있어 다시 추가합니다

[BM-383] :bug: claims role 가져오는 부분 추가
